In [1]:
pip install pandas

In [2]:
pip install sklearn

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [3]:
import pandas as pd
import numpy as np

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
sms_data = pd.read_csv("/content/drive/MyDrive/spam.csv", encoding='latin-1')

In [11]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
stemming = PorterStemmer()
corpus = []
for i in range (0,len(sms_data)):
  s1 = re.sub('[^a-zA-Z]',repl = ' ',string = sms_data['v2'][i])
  s1.lower()
  s1 = s1.split()
  s1 = [stemming.stem(word) for word in s1 if word not in
        set(stopwords.words('english'))]
  s1 = ' '.join(s1)
  corpus.append(s1)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer =CountVectorizer()

In [15]:
x = countvectorizer.fit_transform(corpus).toarray()
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
y = sms_data['v1'].values
print(y)

['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,
stratify=y,random_state=2)

In [18]:
#Multinomial Naïve Bayes.
from sklearn.naive_bayes import MultinomialNB
multinomialnb = MultinomialNB()
multinomialnb.fit(x_train,y_train)

MultinomialNB()

In [19]:
# Predicting on test data:
y_pred = multinomialnb.predict(x_test)
print(y_pred)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [20]:
#Results of our Models
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [22]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print("accuracy_score: ",accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1448
        spam       0.92      0.93      0.92       224

    accuracy                           0.98      1672
   macro avg       0.95      0.96      0.96      1672
weighted avg       0.98      0.98      0.98      1672

[[1429   19]
 [  16  208]]
accuracy_score:  0.979066985645933
